### PR TITLE
(feat) Remove drag and drop functionality from interactive builder

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR removes the drag-and-drop functionality from the Form Builder's interactive builder section. This feature isn't working optimally and requires fixing. We've filed [this ticket](https://openmrs.atlassian.net/browse/O3-2400) for tracking the work, and hopefully this functionality gets worked back in soon.

### CODE REVIEW

**Comment by senthil-athiban** [comment]
Before Changes:

https://github.com/user-attachments/assets/4963f3fe-2c52-4bbb-94eb-d810100d5541

After Changes:

https://github.com/user-attachments/assets/37fd5d0d-935b-4550-a62f-36f7631fd15e

@denniskigen, is this issue related to dragging and dropping questions from the source to the destination? If so, we can fix it without removing the entire drag-and-drop feature.

I have attached a demo that shows the functionality of drag-and-drop after the bug fix.

**Comment by denniskigen** [comment]
Absolutely, @senthil-athiban! Mind assigning [this issue](https://openmrs.atlassian.net/browse/O3-2400) to yourself and working on the fix?

**Comment by senthil-athiban** [comment]
Sure @denniskigen

**Comment by denniskigen** [comment]
Closing in favor of @senthil-athiban’s imminent fix.

**Pull request closed without merging**
