### PR TITLE
(docs) README enhancements

### PR DESCRIPTION
**Pull request by denniskigen**
Enhances the README.

### CODE REVIEW

**Comment by denniskigen** [comment]
@gracepotma, beat me to it 😉

**Comment by gracepotma** [comment]
Ahhh I'm so sorry Dennis - this is a lesson learned for me to check open PRs :/

**Comment by gracepotma** [comment]
But looks like most of your content here should still go into the ReadMe!!

**Comment by gracepotma** [comment]
Happy to merge this but tbh I don't know how to resolve the conflicts.

**Comment by denniskigen** [comment]
Worry not, @gracepotma. This is about as mundane a PR as they come. I've fixed the conflicts. Feel free to merge whenever.

**Pull request merged**
