### PR TITLE
(feat) O3-3638: Enable reordering questions across sections using drag-and-drop

### PR DESCRIPTION
**Pull request by Twiineenock**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

### Overview

This PR enhances the drag-and-drop functionality for questions within the form builder. Previously, clients could only move questions within a single section on a page. This improvement expands the capability, allowing for more flexible question management.

### Key Enhancements

This PR introduces the following enhancements:

- [x] Ability to move a question within a given section.
- [x] Ability to move a question across sections on the same page.
- [x] Ability to move a question across sections on different pages.

For further details, please refer to the [Issue Ticket O3-3638](https://openmrs.atlassian.net/browse/O3-3638).

## Related Issue

[https://openmrs.atlassian.net/browse/O3-3638](https://openmrs.atlassian.net/browse/O3-3638)

## Screancast
Here is the UX now:

[dnd.webm](https://github.com/user-attachments/assets/99cc98e7-4aa8-4311-a6bd-53d7d00bfa2a)

### CODE REVIEW

**Comment by Twiineenock** [comment]
Hi @NethmiRodrigo , @denniskigen, A review request here.

**Comment by Twiineenock** [comment]
FYI @hadijahkyampeire

**Comment by VeronicaMuthee** [comment]
@Twiineenock i am super excited to see drag-and-drop now working across sections - thumbs up for that

**Review by NethmiRodrigo — COMMENTED** [review]
LGTM! Thank you very much @Twiineenock! Great work, I know a lot of people who would benefit from this!
One minor thing, could you please see if we can add e2e/unit test coverage for this?

**Comment by denniskigen** [comment]
Thanks for working on this, @Twiineenock. It looks like the current logic won't let you move a question from a section if it's the section has only one question. If that's intended, I think it's fine. Otherwise, we'll probably need to figure out how to explicitly handle the case whether a section becomes empty after moving its only question.

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks, @Twiineenock.

**Review by denniskigen — APPROVED** [review]
LGTM

**Comment by denniskigen** [comment]
@NethmiRodrigo Added some test coverage. It doesn’t cover all scenarios with the interactive builder, but it lays the foundation for future improvements.

**Review by denniskigen — APPROVED** [review]
LGTM

**Pull request merged**
