### PR TITLE
(chore) Automatically extract translation strings

### PR DESCRIPTION
**Pull request by denniskigen**
This PR sets up `i18next-parser` to automatically extract translation keys and strings from our code.

### CODE REVIEW

**Comment by denniskigen** [comment]
Are you aware of this type error, @pirupius?

Screenshot 2022-12-13 at 20 58 06

**Comment by pirupius** [comment]
@denniskigen this is stemming from the rewrite of `i18next` to in typescript in version 22.  So the build issues go upto the `esm-utils` in the `esm-core`  

see 2 options, 
1. Downgrade you package versions for i18next
2. Upgrade the whole framework

**Comment by pirupius** [comment]
The build seems to pass when these package versions 

```
"i18next": "^19.7.0",
"i18next-parser": "^5.4.0",
"react-i18next": "^11.18.6",
```

**Comment by denniskigen** [comment]
Should be good to go. Thanks, @pirupius.

**Review by pirupius — APPROVED** [review]

**Pull request merged**
